application/libraries/REST_Controller.php
Fixing to check if $_SERVER['HTTPS'] is non-empty instead of specifically 'on'.
According to PHP documentation this variable is "[s]et to a non-empty value if the script was queried through the HTTPS protocol." This caused incorrect 403 errors with a separate library that set the variable to "On" instead of "on". (http://php.net/manual/en/reserved.variables.server.php)
=> Update _detect_ssl() to allow all valid values

application/libraries/REST_Controller.php
Fix for issue #408
Updated _parse_put(), _parse_patch() and _parse_delete() functions to use CodeIgniter Input Class `$this->input->input_stream()` to fix conflicts between CI and the Restserver.
Also using `$this->input->method()` to check we have right type of request.
=> Fix for issue #408

application/libraries/REST_Controller.php
As noted here https://github.com/chriskacerguis/codeigniter-restserver/issues/412#issuecomment-90352038
=> Fixed Missing rest_enabled_logging check for response code logging

application/libraries/REST_Controller.php
According to Code Igniter documentation, those functions are deprecated in 3.0 and will be removed on 3.1
-  http://www.codeigniter.com/user_guide/installation/upgrade_300.html#uri-routing-methods-fetch-directory-fetch-class-fetch-method
- http://www.codeigniter.com/user_guide/installation/upgrade_300.html#input-library-method-is-cli-request
=> updated deprecated funtions in CI 3.0

application/libraries/Format.php
JSON_NUMERIC_CHECK has been introduced with this commit: https://github.com/chriskacerguis/codeigniter-restserver/commit/e14659617b35a822a1df365b8203b038c0f8a100
This commit reverts JSON_NUMERIC_CHECK partly: https://github.com/chriskacerguis/codeigniter-restserver/commit/776a0fcfeb265ad9281114d8b5e28fe01b9d3917
I am proposing a full removal.
=> Complete removal of JSON_NUMERIC_CHECK.

application/libraries/REST_Controller.php
As the current library is geared towards CI3, it's perhaps good to start using the same approach CI3 has with user's being able to pass NULL for xss_clean, that then defaults to the user's global choice for global xss filtering
This was created by another user
=> Removed a bug and CI3's approach to xss_clean

README.md, application/controllers/api/Example.php, application/controllers/api/Key.php, application/libraries/Format.php, application/libraries/REST_Controller.php
A new method called $this->query() has been added, that works just the same as it's counterparts e.g. $this->get(), $this->post(), though only for query parameters. This has basically been moved out of $this->_parse_get() into a separate function ($this->_parse_query()), and now means the query parameters can be used regardless of whether it's a GET request (as these were only being being parsed for a GET request).
I have also added class-level constants which denote the popular HTTP status codes for RESTful APIs e.g. REST_Controller::OK or REST_Controller::NOT_FOUND, thus doing away with awful ["magic numbers"](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants)
There are also a couple of fixes too.
=> An addition that fixes #405, constants and various code tweaks

application/libraries/REST_Controller.php
$row was returned instead of TRUE. The test at line 509 failed therefor.
=> function _detect_api_key should return boolean

application/config/rest.php
Issue #530 Set the response_code field in the logs table to have a default of '0'.
=> Fix for issue #530 Field 'response_code' doesn't have a default value

application/views/rest_server.php, application/views/welcome_message.php
Some long-text links did not fit when a page is narrowed.
=> A minor visual correction.

application/controllers/api/Key.php
`$this->security->get_random_bytes()` returns binary string.
So this sample controller does not work now.
=> Fix _generate_key() method. See #535

application/libraries/REST_Controller.php
=> Refactor REST_Controller::_parse_options()

application/config/rest.php
Added missing `user_id` field for `keys` database structure in rest config file.
=> Config file database structure missing field.

application/libraries/Format.php
The PHP ini directive zend.ze1_compatibility_mode was removed in PHP 5.3. Because this library supports PHP 5.4+, there is no longer any need to have this check in the code base
=> Removing zend.ze1_compatibility_mode check

application/libraries/REST_Controller.php
If you are making JSON requests to the server everything is working fine when using POST method, but in case of PUT request no variable is showing up. In fact only url_encoded requests are accepted in PUT request. 
This commit solves the problem in case of JSON request by parsing the body and assigning it to the put_args in order to make it work with Angular2 or other JavaScript requests.
=> In case of json put request parsed body in order to get the parameters.

application/libraries/REST_Controller.php
I think that is better to use 405 as response code in this case. That's because the reason for this error is that the method is not found/allowed. 
It will be good to have separate cases if method is not declared in the controller and when the HTTP method does not match the expected one.
I also purpose to use exclamation mark in the if instead of ```method_exists($this, $controller_method) === FALSE```. It is shorter and since (method_exits())[http://php.net/manual/en/function.method-exists.php] returns boolean, I do not see a problem to do it ;).
=> Response code changed

application/config/rest.php, application/libraries/REST_Controller.php
For cases where you want a particular api-key to have access to all controllers, it is better to have a flag to indicate that instead of having a row for each controller in the access table.
=> _check_access() flow change

application/libraries/Format.php
without the parameter JSON_NUMERIC_CHECK the json_encode function is ignoring the integer values from a array or database and then the integer values are serialized into a string.
=> fix json_encode for integer values

application/libraries/REST_Controller.php
Quickly deactivate API KEY's from accessing your API in case you do not wish to always go to database, change keys, etc
=> Check if API KEY submitted is activated

src/chriskacerguis/codeigniter-restserver/Rest_server.php
The path when installed needed to go one level further back than the original code was - added an additional `../` to be in the right place.
=> Update path to config file in Rest_server.php

.gitignore, CHANGELOG.md, application/controllers/api/Example.php, application/controllers/api/Key.php, application/libraries/Format.php, application/libraries/REST_Controller.php
- Using PHPStorm's code inspection, I elliminated some problems with PHP Doc, and what they call "Code Smell"
- Added support for CodeIgniter controller's index methods (index_GET, index_POST...)
- You can now create a controller, ex `countries`, and have a method `index_get()` such that a request to: `/countries` will trigger it. Also, you can have `index_get($code)` so `/countris/US` will trigger it
- This supports REST standards. `/countries` can list, can get, can post, can put, can patch, and can delete
- Added exceptions handling when the method could not be found
- My suggested exceptions handler was added, but I take it back, and instead I added a usage of global CI_Exceptions/MY_Exceptions handler
=> Code smell, PHP Doc problems, Index methods, and global exception handler

application/libraries/REST_Controller.php
cross site request first can use option http method.
but use `keys` authentication, authentication can fail
=> fix cross site to option request error

application/libraries/REST_Controller.php
_prepare_basic_auth and _prepare_digest_auth methods should pass authentication type to force_login method. Otherwise auth overriding doesn't work properly.
=> REST_Controller auth override fix

application/libraries/REST_Controller.php
In PUT requests where the payload does not have a defined name (e.g JSON object) the request body should get the raw input stream.
=> Fetching the request body in PUT requests

application/libraries/REST_Controller.php
Inserting a space first and then a comma seems wrong to me. Was this intended?
Why `Origin ,X-Requested-With ,Content-Type ,Accept ,Access-Control-Request-Method` instead of `Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method`?
=> Insert comma and then a space in allowed headers and methods.

application/libraries/Format.php
As per this answer: https://stackoverflow.com/questions/4348802/how-can-i-output-a-utf-8-csv-in-php-that-excel-will-read-properly/16766198#16766198
If csv content encoding is not converted, special characters will not work in Microsoft Excel (but will work eg. in Notepad++). After encoding conversion MS Excel will show special characters properly.
(My first PR ever so hope I did everything by the book!)
=> Added csv output encoding conversion from UTF-8 to UTF-16LE

application/helpers/db_helper.php, application/helpers/index.html, application/language/portuguese-brazilian/rest_controller_lang.php, application/migrations/20170706025420_create_table_users.php, application/migrations/20170706030520_create_table_api_keys.php, application/migrations/20170706031435_create_table_api_logs.php, application/migrations/20170706032133_create_table_api_access.php, application/migrations/20170706032825_create_table_api_limits.php, application/migrations/index.html
Add InnoDB Relational Tables with Migrations.
The `db_helper` must be loaded to use Foreign Keys in migrations.
If you accept this PR, can add a info in the README.md or I created a simple controller to do the migration, but is not in the PR. I can add if necessary.
Sorry for the unnecessary commits. I added a wrong file.
=> Migrations

application/libraries/Format.php, application/libraries/REST_Controller.php
For project using composer to install resetserver,
this commit allow developer to use REST_Controller without the need to
copy Format.php to project's application/libraries folder.
=> Using composer to autoload Format library.

application/config/rest.php, application/libraries/REST_Controller.php
Force the use of api key and authentication if selected in the config.
This also resolves the issue with basic authentication being accepted with every request.
=> Force validation 

application/libraries/REST_Controller.php
Access to non-existent controllers and methods should not update request time and request methods
> A Database Error Occurred
> 
> Error Number: 22P02/7
> 
> ERROR: invalid input syntax for integer: "" LINE 2: WHERE "id" = '' ^
> 
> UPDATE "api_logs" SET "response_code" = 404 WHERE "id" = ''
> 
> Filename: third_party/restserver/libraries/REST_Controller.php
> 
> Line Number: 2208
=> Fix: A Database Error Occurred when update logs

application/libraries/Format.php
Special chars, such as "ç" and "ã", that are abundant in my language (portuguese) were being transformed into strange things. with this change, they're showing up just right...
=> special chars encoding

application/libraries/REST_Controller.php
If the `check_cors` and `rest_enable_logging` options are both enabled, an OPTIONS request will cause a fatal error:
1. the `_check_cors` function will end with an `exit` statement;
2. the class destructor will try to write to the log table;
3. however, the database class is not yet loaded at this point.
In this fix, `_check_cors` will load the database if necessary before `exit`.
=> bugfix: fatal error if check_cors and rest_enable_logging are both enabled

application/migrations/20170706030520_create_table_api_keys.php, application/migrations/20170706031435_create_table_api_logs.php, application/migrations/20170706032133_create_table_api_access.php, application/migrations/20170706032825_create_table_api_limits.php
Setting up a Codeigniter Migration the "rest" config needs to be loaded so the config variables are properly loaded.
=> load rest config, correct missing vars - Migrations (#820)

application/config/rest.php, application/libraries/REST_Controller.php
My front-end framework (Sencha Ext JS) requires the server to set the header Access-Control-Allow-Credentials to true if using a REST Proxy. Added a setting to the config file to allow this.
=> Add config to force CORS pre-flight headers to be included

application/libraries/REST_Controller.php
Move output format detection upwards,
to allow responses earlier:
As I have added a custom format via `as_*`, `_from_*` as subclass (#946), I want to realize error handling.
Therefore output must already be possible, when Format::factory is run.
=> Move output format detection upwards

application/libraries/REST_Controller.php
This will avoid calling the method _auth_override_check() in case of need to check overrides within a controller.
I also cleared out some unnecesary space in line 390.
=> private variable $auth_override made protected

application/libraries/REST_Controller.php
Fixes issue #1023 
The added lines returns the response to the client and allows code to continue executing. 
`ob_end_flush; ` does not actually work correctly according to https://stackoverflow.com/questions/10579116/how-to-flush-data-to-browser-but-continue-executing 
It is kept for legacy compatibility and to prevent regressions.
=> QUICKFIX Continue Returns Response

src/RestController.php
CORB protection was added to Chromium based browsers to add further cross-origin resource loads protection.
Details about the protection here : https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md
Without this update, some AJAX requests from those browsers fall in the CORB and fail.
The update consists of sending the right Content-Type header for callback encapsuled JSON output : application/javascript instead of application/json
=> response method update for CORB protection

src/RestController.php
Hi! Is my first pull request.
I found an undefined variable.
I try collaborate with the codeigniter community.
I not found tickets for this problem.
(Sorry for my bad english)
Thanks.
=> Repair undefined variable.

src/RestController.php
Add "self::" before the http constants for prevent php 7 warning of undefined constants
=> Prevent php 7 warning of undefined constants

src/RestController.php
Bug fix: Load config before call it.
The rtime was never registered because the configuration was loaded later.
=> Bug fix: Load config before call it

src/RestController.php
Fix $valid_response on _prepare_digest_auth() using md5(username:restrealm:password) from _check_login()
=> Fix digest authentication

src/RestController.php
This commit: 
- https://github.com/chriskacerguis/codeigniter-restserver/commit/750b92820a1408b31bff4812207396c92f977ac8
deleted the fixes of these commits:
- https://github.com/chriskacerguis/codeigniter-restserver/commit/d708cbbb8ddc3e4beae2030e3f44b3434d896fdd
- https://github.com/chriskacerguis/codeigniter-restserver/commit/3aa10fe1f48eca967cc5e63bfd2a7ef20f75591d
=> Restoring deleted fixes

src/RestController.php
Fixes PHP 8.1 deprecation notice when trying to `strtolower` `NULL`
=> Don't attempt to lowercase a NULL

src/Format.php
Addresses PHP 8.1+ compatibility (if you passed null to `html_entity_decode()` , it's not happy about it
=> Fix handling null in to_xml()

README.md, src/Format.php, src/RestController.php
This patch allows the class to be extended in a way that additional outputs can be defined.
General workflow
- Extend `Format` class to define addtional to_ methods (for example `to_pdf`)
- Extend the `RestController` method to define the `format` variable
In the old version this was possible by replacing the `Format` class entirely (because it wasn't using name spaces, it could be replaced). This is back-porting this functionality in a way.
=> Allow extending formats

src/RestController.php, src/rest.php
Adds basic support for expiring api keys by checking if the enable flag is configured, and compares the timestamp in the configured column to the current system unix time using time() function
=> Add support for expiring api keys
