- application/libraries/Format.php
Added docblocks o it can added in the Apigen generated documentation files.
> Add docblocks to format.php 

- application/config/rest.php
- application/libraries/REST_Controller.php
Was in discussion, Tjoosten asked for a pull request
https://github.com/chriskacerguis/codeigniter-restserver/issues/412#issuecomment-89636836
> Response Code Logging

- application/libraries/Format.php
- application/libraries/REST_Controller.php
else if is a incorrect method.
referring to: http://php.net/manual/en/control-structures.elseif.php
> correct else if

- application/libraries/Format.php
Before : 
{
"id": "132"
}
After:
{
"id": 132
}
> Add JSON_NUMERIC_CHECK for auto convert string to int

- application/libraries/REST_Controller.php
CI1.x obviously is not supported.
> Removing an obsolete fragment of code.

- application/config/rest.php
- application/libraries/REST_Controller.php
The following commits are about moving towards a CodeIgniter 3 like structure
> Updated the layout and comments of rest.php

- application/libraries/REST_Controller.php
Continuing to put my mark on this very useful library =)
> Removed the pre tag and rewrote the blacklist function

- application/libraries/REST_Controller.php
- application/libraries/index.html
The style guide can be found [here](http://www.codeigniter.com/user_guide/general/styleguide.html)
This also contains bug fixes and performance fixes
> Adhering to the style guide of CI3

- application/libraries/Format.php
- application/libraries/REST_Controller.php
Corrections, mainly about the controller instance usage.
> Polishing about #477.

- application/libraries/Format.php
No clue as to why that other commit is there though.
> Fixed issue with $data being undefined

- application/libraries/Format.php
> Fixed left over underscore from testing function

- application/libraries/REST_Controller.php
API calls time limit is now configurable.
Example:
```
$this->methods = ['methodname_get' => ['level' => 0, 'limit' => 1, 'time' => 60 * 60 * 24]];
```
Limit doesn't depend on url extension (doesn't solve #397 )
I finally had time to resolve the conflicts. ur feeling lucky. :8ball: ;)
> api calls time limit. 4th attempt

- application/config/rest.php
- application/libraries/REST_Controller.php
Referencing issue #467.
Added a new config definition.
> Auth Override for HTTP Methods types. Adding 'auth_override_class_method_http' config.

- application/config/index.html
- application/config/rest.php
- application/config/routes.php
- application/controllers/Rest_server.php
- application/controllers/Welcome.php
- application/controllers/api/Example.php
- application/controllers/api/Key.php
- application/controllers/api/index.html
- application/controllers/index.html
- application/libraries/Format.php
- application/libraries/REST_Controller.php
- application/views/index.html
- application/views/rest_server.php
- application/views/welcome_message.php
* I removed a wrong idea of mine within REST_Controller and updated the example API accordingly. URIs like users/{id} as an alternative of the ordinary users/id/{id} should be supported by using routing rules. I added a configuration routes.php for such a demonstration.
* I suppressed some possible "array to string conversion" notices within Format.php.
* I added a modified "Welcome" page and a page for quick testing the REST server (a list of sample links). This is for convenience, otherwise people are not motivated to test.
> Summary updates and adding simple pages for quick test

- application/config/routes.php
- application/controllers/Welcome.php
This is unlikely to change in the stable release
> Updated files to match CI 3.0.1rc

- application/libraries/Format.php
Now matches the same style as CodeIgniter
> Renamed _CI variable

- application/libraries/REST_Controller.php
adding session override type for specific class/method and for 'class/method/HTTP method'
> Session auth override

- application/config/rest.php
- application/libraries/REST_Controller.php
This is something I would like to use (so I can continue to use limits etc per key but have users authenticate) so thought it might be worth putting in here for others to use (or not!)
> Added the ability to use both authentication and API Keys

- application/language/french/index.html
- application/language/french/rest_controller_lang.php
I added support for the french language for codeigniter-restserver. The french version is a translation of the english one.
> Add french language support

- application/libraries/REST_Controller.php
Authorization: Old PR #616 changes included here, explanation there. 
Solved #617
> Corrections on auth_override and Reading Authorization 

- application/language/traditional-chinese/index.html
- application/language/traditional-chinese/rest_controller_lang.php
Add traditional chinese language support.
> Add traditional chinese language support.

- application/config/rest.php
- application/language/bulgarian/rest_controller_lang.php
- application/language/english/rest_controller_lang.php
- application/language/french/rest_controller_lang.php
- application/language/german/rest_controller_lang.php
- application/language/greek/rest_controller_lang.php
- application/language/portuguese-brazilian/rest_controller_lang.php
- application/language/romanian/rest_controller_lang.php
- application/language/serbian_cyr/rest_controller_lang.php
- application/language/serbian_lat/rest_controller_lang.php
- application/language/simplified-chinese/rest_controller_lang.php
- application/language/spanish/rest_controller_lang.php
- application/language/traditional-chinese/rest_controller_lang.php
- application/language/turkish/rest_controller_lang.php
- application/libraries/REST_Controller.php
You can set request limit with or without rest key by ip address.
> Limit request by ip address - with or without rest key

- application/language/dutch/index.html
- application/language/dutch/rest_controller_lang.php
I've added a dutch translation that I use in one of my applications
> added dutch translation

- application/language/bulgarian/rest_controller_lang.php
Signed-off-by:Ivan Tcholakov <ivantcholakov@gmail.com>
> Bulgarian language update.

- application/language/indonesia/index.html
- application/language/indonesia/rest_controller_lang.php
Signed-off-by:Barayuda Gautama saya.bara@gmail.com
> Add Indonesian language

- application/libraries/REST_Controller.php
[As mentioned here](https://github.com/chriskacerguis/codeigniter-restserver/issues/713), response did the same for me, regardless if $continue was true or false. This fixed the issue for me.
> response continue fix

- .gitignore
- CHANGELOG.md
- README.md
- application/config/rest.php
- application/controllers/api/Example.php
- application/controllers/api/Key.php
- application/libraries/Format.php
- application/libraries/REST_Controller.php
Here are changes I forgot to merge a long time ago.
Every commit is self explanetory
> All around cleaning

- application/controllers/api/Key.php
> bug fix request

- application/libraries/Format.php
- application/libraries/REST_Controller.php
- composer.json
This changes enable "composer require " usage with namespaces.
> Add namespaces support

- application/language/portuguese-brazilian/rest_controller_lang.php
> Update missed line

- application/libraries/REST_Controller.php
> Limits not working

- application/libraries/REST_Controller.php
Remap function is testing for several cases of invalid requests. In some cases it "return"s when validation fails. In other cases it just adds an error response, and continue to execute. This cause endpoints to be called for failed requests (unauthorized, unauthenticated, invalid params etc').
I added a validation flag, fliping it in relevant places, and testing it at the end, before calling the endpoint.
> Fix - don't call API endpoint if request is not valid.

- README.md
This is based on issues #761 
Thank you.
> Adding require once to make REST_Controller work properly

- application/libraries/Format.php
Add optional key value of '_value' to allow for generating an XML element that has both a string value and one or more attributes.
> Add ability to create an XML element with both a string value and one or more attributes

- application/language/korean/index.html
- application/language/korean/rest_controller_lang.php
* Added Korean language translation
* Create default index.html
> Korean language support

- README.md
- application/libraries/Format.php
- application/libraries/REST_Controller.php
- composer.json
In this PR i created the Restserver as composer ready and as possibility for include in library.
But now there is a namespace. I Think we can remove it to have backward compatibility but its a bit dirty. What do you think?
> Codeigniter Composer Ready

- README.md
- application/libraries/REST_Controller.php
Issue #840
- Fix: format initialization without composer
- Fix: Readme
> Bugfix: Using without Composer, Format-Error

- AUTHORS.md
> Issue #849 Adding AUTHORS.md

- application/config/config.php
- application/config/hooks.php
- application/config/profiler.php
- application/hooks/hooks.profiler.php
- application/libraries/REST_Controller.php
Codeigniter Profiling Feature added
> Codeigniter Profiling Feature added

- application/config/ldap.php
- application/config/profiler.php
- application/config/rest.php
- application/config/routes.php
- application/controllers/api/Example.php
- application/controllers/api/Key.php
- application/migrations/20170706025420_create_table_users.php
- application/migrations/20170706030520_create_table_api_keys.php
- application/migrations/20170706031435_create_table_api_logs.php
- application/migrations/20170706032133_create_table_api_access.php
- application/migrations/20170706032825_create_table_api_limits.php
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- README.md
This can sometimes be confusing as we programmers just copy-paste the example on the readme when we're excited about using an amazing library for the first time
Check this [Stack Overflow question](https://stackoverflow.com/q/58218025/5581565)
> add import to handling requests example

- src/RestController.php
Replace old http_status array by http status constants.
> Replace old http_status array by http status constants

- src/RestController.php
- failed load custom rest config
- failed access constant HTTP return code
> ^ Fix Bugs : Failed load application/config/rest.php

- src/RestController.php
Please review my changes.
There were some issues need to be fixed.
> For fixing use of undefined constant issue

- src/RestController.php
I believe this takes care of issue 1069. Feel free to decline if there is a problem in my implementation.
> Attempt to fix issue 1069 - XSS filtering

- src/RestController.php
Fixes https://github.com/chriskacerguis/codeigniter-restserver/issues/1111
> Fix RecursiveIteratorIterator not found
